# ========== 自定义 ==========
# 服务端口号
server:
  port: 8080

# 代理配置
proxy:
  # 访问目标站点所用代理（除 free-ss）
  enable: true
  host: 127.0.0.1
  port: 1080

  # 访问 free-ss 时所用代理
  free-ss:
    enable: false
    host: 113.12.72.24
    port: 3128
    socks: false


# driver 路径
driver:
  path: lib\MicrosoftWebDriver.exe


#  因 Heroku 应用 30 分钟没有访问会自动休眠，为防止休眠，系统每 20 分钟访问一次该配置地址
health:
  url:
  cron: 0 0/20 6-23 * * ?


# spring boot 启用调试模式
debug: true


# ========== Spring ==========
spring:
  # Spring 数据库
  datasource:
    platform: h2
    driver-class-name:  org.h2.Driver
    url: jdbc:h2:./data/db
    username: sa
    password: